FST: Add missing noexcept specification in ErrorReport
Fails to compile with clang with:

fst/storage/ErrorReport.cc:37:10: error:
'ErrorReport' is missing exception specification 'noexcept'