ARCHIVE: Fix archive put error due to missing Python imports
2025-06-03 09:43:52,215 transfer[2372840] eosarch_run.py:82 LVL=ERROR name 'NotOnTapeException' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/eosarch/transfer.py", line 254, in run
    self.do_transfer()
  File "/usr/lib/python3.9/site-packages/eosarch/transfer.py", line 379, in do_transfer
    self.wait_on_tape()
  File "/usr/lib/python3.9/site-packages/eosarch/transfer.py", line 1099, in wait_on_tape
    timeout = randrange(min_timeout, max_timeou)
NameError: name 'randrange' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/eosarch_run.py", line 72, in <module>
    tx.run()
  File "/usr/lib/python3.9/site-packages/eosarch/transfer.py", line 255, in run
    except NotOnTapeException as _:
NameError: name 'NotOnTapeException' is not defined