CONSOLE: Check that the MGM is online and reachable before executing any command. Fixes EOS-1292
The default timeout resolution in XRootD is 15 seconds therefore if the MGM is
not online the user will receive a message in the console similar to the following:

[esindril@esdss000 build]$ time ./console/eos root://localhost:1099//
error: MGM root://localhost:1099// not online/reachable

real    0m15.019s
user    0m0.009s
sys     0m0.009s