FST: Assign correct number of written bytes
Fixes the warning below.

[ 29%] Building CXX object fst/CMakeFiles/eoscp.dir/eoscp.cc.o
fst/eoscp.cc: In function ‘int main(int, char**)’:
fst/eoscp.cc:2597:14: error: ignoring return value of
‘ssize_t write(int, const void*, size_t)’ declared with attribute
  ‘warn_unused_result’ [-Werror=unused-result]
 2597 |         write(dst_handler[i].first, ptr_buffer, nread);