NS: Fix compiler warnings in utils/Buffer.hh
Put const in the correct place or remove from return type, and
use the base class constructor explicitly.

In file included from namespace/interface/IContainerMD.hh:29,
                 from namespace/interface/IFileMD.hh:28,
                 from namespace/PermissionHandler.hh:26,
                 from namespace/PermissionHandler.cc:24:
namespace/utils/Buffer.hh: In copy constructor
  ‘eos::Buffer::Buffer(const eos::Buffer&)’:
namespace/utils/Buffer.hh:56:3: error: base class ‘class std::vector<char>’
should be explicitly initialized in the copy constructor [-Werror=extra]
   56 |   Buffer(const Buffer& other)
      |   ^~~~~~